Appsrn 286 agregar utils de device info y net info
janis-commerce/app-device-info pull request #2
Opened 2024-03-20 15:02 UTC by GonzaFran

LINK DE TICKET: *

https://janiscommerce.atlassian.net/browse/APPSRN-280

DESCRIPCIÓN DEL REQUERIMIENTO: *
CONTEXTO

Actualmente, en todos los repos de aplicaciones y packages (request, crashlytics y analytics) del equipo de apps se viene repitiendo un comportamiento…

Si necesitamos obtener información sobre el dispositivo en el que estamos ejecutando una aplicación o una función, usamos los métodos de la librería https://www.npmjs.com/package/react-native-device-info. Estas dependencias y sus métodos ofrecen datos cómo:

    la marca del dispositivo.
    el modelo.
    el id único del dispositivo.
    el sistema operativo

y muchos más…

Sin embargo no contiene información sobre la conexión a internet, la cual, en una aplicación que opera con internet, puede ser un dato bastante relevante para manejar cuando realizar (o no) una request. En este caso, para resolver este inconveniente, usamos la dependencia de https://www.npmjs.com/package/@react-native-community/netinfo que provee la información necesaria respecto a la conectividad. 

Al no tener un package propio del que obtener esta información caemos en el problema de, si actualizamos una versión por “X” funcionalidad nueva, tener que actualizar todo en cada repositorio y package que requiera y use la información del dispositivo del usuario.
NECESIDAD

Armar un package que, utilizando y unificando las 2 dependencias mencionadas, se encargue de obtener la información del dispositivo del usuario, la situación de la conectividad a internet y que, a futuro, nos permita meter más métodos para obtener la información que creamos necesaria directamente de él.

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se ajustaron versiones de dependencias para el package, para la validación de código y para el desarrollo de métodos.
El package exporta TODOS los métodos y funciones que provee la librería[ react-native-device-info](https://www.npmjs.com/package/react-native-device-info).
También exporta el hook useNetInfo que da la librería [react-native-community/netinfo ](https://www.npmjs.com/package/@react-native-community/netinfo)

El package también tiene métodos propios que van a servir para obtener información acerca de la conexión a internet y la información del dispositivo, entre ellos están:

- `getDeviceModel`, que devuelve un string con la marca y modelo del celular.
- `getOSVersion`, que devuelve un string con el sistema operativo y el número de versión.
- `getDeviceScreenMeasurements`, que devuelve las medidas de pantalla del dispositivo.
- `getDeviceInfoForHeaders`, es una utils que se hizo para obtener la información que usamos en los headers de janis

También se armaron 2 utils asincronicas en base a netInfo:

`getNetworkState`, que retorna un objeto con información acerca del estado de la conexión, con el tipo de conexión, la fuerza que tenga, el nombre del proveedor y si la internet es accesible.

DATO:
Si la conexión es wifi, lo que se muestra como proveedor es la dirección IP.
Si la conexión es de tipo celular, lo que se muestra es el nombre del proveedor de telefonía movil.

`GetInternetReachability` retorna un booleano que explicita si la conexión a internet está disponible o no.

CÓMO SE PUEDE PROBAR? *

Para probarlo hay que vincular el package al repositorio local con yalc.
También es un requisito tener las dependencias react-native-device-info y netInfo instaladas en el repositorio (ya están instaladas en los repos de las apps).

Para importar cualquier metodo hay que importarlo en el archivo que quieras usarlo de la siguiente manera:

```js
import {getDeviceModel, getNetworkState} from '@janiscommerce/app-device-info';

const getDeviceData = async () => {
  const networkState = await getNetworkState();
  const deviceModel = getDeviceModel()
}

```

DATOS EXTRA A TENER EN CUENTA:

Al tratar de importar algún método seguramente te aparezcan muchos metodos porque estamos exportando todo lo que contenga device-info, por lo que, para probar los métodos que armamos para este package, te va a convenir usar los nombres que están en la DESCRIPCIÓN DE LA SOLUCIÓN.

2024-03-20 17:14 UTC, Maukr requested changes
Buenass!
Lo veo todo bien y en picking funciona correctamente, lo único que veo que podríamos agregar es que en `getNetworkState` devolver en una key nueva los `details` restantes en caso que los necesitemos

2024-03-21 16:23 UTC, GonzaFran reviewed
@Maukr listo los cambios comentados

2024-03-21 16:23 UTC, GonzaFran commented on lib/netInfo.js
> +				details: lastDetails,
@Maukr agregué el cambio para que el resto de detalles del state queden dentro de una key "details" en el objeto que retorna la función.

2024-03-21 16:23 UTC, GonzaFran commented on lib/index.js
> +	refresh,
@Maukr al final, sólo exporté el resto de métodos del package netinfo porque, sino, iba a exportar los tipos y clases del package y no es algo que estemos usando en los repositorios.

2024-03-21 17:21 UTC, Maukr approved these changes
Listo!
No vería mal igualmente exportar `export * from '@react-native-community/netinfo';` así devolvemos todo como con 'react-native-device-info'. Igualmente al no ser necesario considero que que está OK.

2024-03-21 18:15 UTC, pablonortiz approved these changes
Estuve probando los distintos métodos en Delivery y lo vi todo perfecto

2024-03-26 20:25 UTC, pablodamianberdun approved these changes

2024-03-26 20:25 UTC, merged